[package]
name = "speech-dispatcher-sys"
version = "0.4.2"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
repository = "https://gitlab.com/ndarilek/speech-dispatcher-rs"
description = "speech-dispatcher system bindings"
license = "LGPL-2.1"

[build-dependencies]
bindgen = "0.52"
gcc = "0.3"
